### PR TITLE
Update kingdom-of-bretonnia.json

### PR DESCRIPTION
**Pull request by naivm**
removed restriction notes from names

### CODE REVIEW

**Comment by nthiebes** [comment]
Thank you for aligning that across multiple factions! 🎉

Only one comment for all of them is that it should be an object like:

```
"notes": {
        "name_en": "0-1 per army",
        "name_de": "0-1 per army",
        "name_es": "0-1 per army",
        "name_fr": "0-1 per army",
      }
```

**Comment by naivm** [comment]
ahh dam i put the [] around them right? sorry

**Comment by nthiebes** [comment]
And the = should be a : 🙃

**Comment by naivm** [comment]
dam im tired heheh

**Pull request merged**
