### PR TITLE
Fix dark-elves.json

### PR DESCRIPTION
**Pull request by TheMost82**
Allow option to reset armor to none for Shades.
Previously you had to delete the Shade unit to reset it.

### CODE REVIEW

**Comment by nthiebes** [comment]
Thanks! I'd suggest moving the light armour option top “options” so it's just a checkbox.

**Comment by TheMost82** [comment]
Hi, thanks for the reply! 
I also considered that option - but then decided to leave it in the Armor Option for consistency with the other Troops Armor options in the UI.
Maybe give it another quick thought with that reasoning, if you then still prefer your solution, i'll happily rework my pr :)
Cheers!

**Comment by nthiebes** [comment]
I agree with you, it obviously makes more sense under armor. Some other units also have it as a generic option, so “No armour” doesn't show up in the list of equipment (also when exporting).

In any case, I'd need to align both versions. It would be perfect if the armor section switches to a checkbox if there's only one option. Implementing that isn't a lot of work, but going through all datasets and aligning it is.

So you can leave it as is or start refactoring 😄. I won't get to it any time soon.

**Comment by TheMost82** [comment]
To be honest - i am intrigued by the automatic armor checkbox switching - already checked the source and seems pretty doable, but i will set up the local dev env first, will have some time next week and then come up with a separate propsal for that.
Thanks for the feedback so far :)

**Pull request closed without merging**
