### PR TITLE
French translations for Bretonnia, Empire and High Elves

### PR DESCRIPTION
**Pull request by Calcipox**
Plus usual fixes in datas.

### CODE REVIEW

**Comment by TheFakeCake** [comment]
Is there a reason not to change _Arcs Courts_ to _Arcs courts_ ?

**Comment by Calcipox** [comment]
No, probably better as Arcs courts, I will change that.

**Comment by TheFakeCake** [comment]
Check for _Arcs longs_ too then ^^

**Comment by Calcipox** [comment]
Yes, in fact after checking, I choose this because it was done like this in the French Rulebook.
Same thing for Arc de Guerre, but all other weapons with multiple words have only one uppercase letter, so probably better to not doing what translators have done in the Rulebook.

**Comment by nthiebes** [comment]
Thanks for also fixing the issues you found 👍.

**Pull request merged**
